-- Create tables if they don't exist
CREATE TABLE IF NOT EXISTS home_sections (
    key TEXT PRIMARY KEY,
    title TEXT,
    description TEXT,
    title_uz TEXT,
    description_uz TEXT,
    title_en TEXT,
    description_en TEXT
);

CREATE TABLE IF NOT EXISTS home_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_key TEXT NOT NULL,
    title TEXT,
    description TEXT,
    title_uz TEXT,
    description_uz TEXT,
    title_en TEXT,
    description_en TEXT,
    icon TEXT,
    sort_order INTEGER DEFAULT 0
);

-- Seed data checks using ON CONFLICT to avoid duplicates
INSERT INTO home_sections (key, title, description, title_uz, description_uz, title_en, description_en) VALUES
('about_preview', 'Интеллектуальный потенциал \nцифровой экономики', 'Альянс объединяет ведущие технологические компании для развития рынка ИИ в Узбекистане. Мы создаем среду для инноваций, объединяя ресурсы бизнеса и науку.', 'Raqamli iqtisodiyotning \nintellektual salohiyati', 'Alyans O‘zbekistonda sun’iy intellekt bozorini rivojlantirish uchun yetakchi texnologik kompaniyalarni birlashtiradi.', 'Intellectual potential \nof the digital economy', 'The Alliance unites leading technology companies to develop the AI market in Uzbekistan.'),
('projects_heading', 'Ключевые проекты', '', 'Asosiy loyihalar', '', 'Key Projects', ''),
('wg_heading', 'Экспертиза и стандарты', 'Мы разрабатываем фундамент для безопасного и этичного ИИ. Эксперты из ведущих компаний формируют повестку дня.', 'Ekspertiza va standartlar', 'Biz xavfsiz va axloqiy sun’iy intellekt uchun poydevor yaratmoqdamiz. Yetakchi kompaniyalar ekspertlari kun tartibini shakllantiradilar.', 'Expertise and Standards', 'We are developing the foundation for safe and ethical AI. Experts from leading companies shape the agenda.'),
('feature_main', 'Роль технологий ИИ \nв развитии компании сегодня', 'Технологии ИИ существенно трансформируют деятельность компаний и станут главным трендом на рынке в течение десяти лет.', 'Kompaniyaning bugungi rivojlanishida \nAI texnologiyalarining o’rni', 'AI texnologiyalari kompaniyalar faoliyatini sezilarli darajada o‘zgartirmoqda.', 'The role of AI technologies \nin company development today', 'AI technologies are significantly transforming company operations.'),
('feature_exp', 'ОПЫТ ПРИМЕНЕНИЯ', 'Альянс создал и активно развивает проект AI Russia, цель которого – продемонстрировать бизнес-сообществу работающие кейсы с использованием искусственного интеллекта.', 'QO‘LLANISH TAJRIBASI', 'Alyans AI Russia loyihasini yaratdi va faol rivojlantirmoqda.', 'APPLICATION EXPERIENCE', 'The Alliance has created and is actively developing the AI Russia project.'),
('mission_left', 'Миссия', 'Быть центром развития искусственного интеллекта в регионе и обеспечивать технологическое лидерство нашей страны и компаний-участников Альянса на глобальном технологическом рынке.', 'Missiya', 'Mintaqada sun’iy intellektni rivojlantirish markazi bo‘lish.', 'Mission', 'To be the center of artificial intelligence development in the region.'),
('mission_right', 'Альянс — открытая структура', 'Для развития искусственного интеллекта необходимо объединять усилия компаний-лидеров в этой сфере. Мы создаем платформу для обмена опытом и совместных проектов.', 'Alyans — ochiq tuzilma', 'Sun’iy intellektni rivojlantirish uchun yetakchi kompaniyalarning sa’y-harakatlarini birlashtirish zarur.', 'Alliance — an open structure', 'To develop artificial intelligence, it is necessary to unite the efforts of leading companies in this field.')
ON CONFLICT (key) DO NOTHING;
