-- Create news_sections table
CREATE TABLE IF NOT EXISTS news_sections (
    key TEXT PRIMARY KEY,
    title TEXT,
    description TEXT,
    title_uz TEXT,
    description_uz TEXT,
    title_en TEXT,
    description_en TEXT,
    cta_button TEXT,
    cta_button_uz TEXT,
    cta_button_en TEXT,
    cta_placeholder TEXT,
    cta_placeholder_uz TEXT,
    cta_placeholder_en TEXT,
    is_active BOOLEAN DEFAULT true
);

-- Create news_stats table
CREATE TABLE IF NOT EXISTS news_stats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value TEXT,
    label TEXT,
    label_uz TEXT,
    label_en TEXT,
    icon_name TEXT,
    sort_order INTEGER DEFAULT 0
);

-- Create news_items table
CREATE TABLE IF NOT EXISTS news_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT,
    excerpt TEXT,
    description TEXT,
    category TEXT,
    read_time TEXT,
    date TEXT,
    
    title_uz TEXT,
    excerpt_uz TEXT,
    description_uz TEXT,
    category_uz TEXT,
    read_time_uz TEXT,
    date_uz TEXT,
    
    title_en TEXT,
    excerpt_en TEXT,
    description_en TEXT,
    category_en TEXT,
    read_time_en TEXT,
    date_en TEXT,
    
    image_url TEXT,
    slug TEXT,
    gallery TEXT[],
    is_active BOOLEAN DEFAULT true,
    is_featured BOOLEAN DEFAULT false,
    sort_order INTEGER DEFAULT 0
);

-- Insert default data for sections
INSERT INTO news_sections (key, title, description) VALUES
('hero', 'Новости и события', 'Узнайте о последних событиях в мире ИИ и деятельности Альянса'),
('header', 'Последние новости', ''),
('newsletter', 'Подпишитесь на рассылку', 'Получайте самые важные новости и анонсы мероприятий прямо на почту'),
('stats_section', 'Секция статистики', '')
ON CONFLICT (key) DO NOTHING;

-- Insert default data for stats
INSERT INTO news_stats (value, label, icon_name, sort_order) VALUES
('50+', 'Мероприятий проведено', 'Calendar', 1),
('10k', 'Участников сообщества', 'Users', 2),
('100+', 'Публикаций в СМИ', 'Newspaper', 3)
ON CONFLICT DO NOTHING;

-- Insert sample news items
INSERT INTO news_items (title, excerpt, description, category, date, read_time, image_url, slug, is_featured, sort_order) VALUES
('Конференция AI Week 2025', 'Крупнейшее событие года в сфере ИИ пройдет в Ташкенте.', 'Полное описание события...', 'Мероприятие', '15 Сен 2025', '3 мин', '', 'ai-week-2025', true, 1),
('Запуск образовательной программы', 'Новый курс для студентов технических вузов.', 'Полное описание...', 'Образование', '10 Сен 2025', '5 мин', '', 'edu-program-launch', false, 2);
